sonar.projectKey=taskflow-api
sonar.projectName=taskflow-api
sonar.sources=.
sonar.tests=tests,e2e
sonar.test.inclusions=tests/**/*.test.js,e2e/**/*.spec.js
sonar.exclusions=node_modules/**,coverage/**,reports/**,playwright.config.js,playwright-report/**,test-results/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
