sonar.projectKey=taskflow-api
sonar.projectName=taskflow-api
sonar.sources=.
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**,reports/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
